# API Configuration Models for SyncCore
# Pydantic models for FastAPI endpoints and PostgreSQL backend

from models.config.api.bridge import (
    Bridge,
    BridgeCreate,
    BridgeList,
    BridgeStatus,
    BridgeType,
    BridgeUpdate,
)
from models.config.api.connector_template import (
    ConnectorTemplate,
    ConnectorTemplateCreate,
    ConnectorTemplateList,
    ConnectorTemplateSummary,
    ConnectorTemplateUpdate,
    TemplateVariable,
    VariableType,
)
from models.config.api.event import (
    Event,
    EventBulkCreate,
    EventCreate,
    EventList,
    EventType,
    EventUpdate,
)
from models.config.api.machine import (
    Machine,
    MachineCreate,
    MachineList,
    MachineProperties,
    MachineStatus,
    MachineSummary,
    MachineUpdate,
)
from models.config.api.organization import (
    Organization,
    OrganizationCreate,
    OrganizationList,
    OrganizationSettings,
    OrganizationStats,
    OrganizationStatus,
    OrganizationUpdate,
)
from models.config.api.user import (
    LoginRequest,
    LoginResponse,
    OrganizationMembership,
    User,
    UserCreate,
    UserList,
    UserRole,
    UserStatus,
    UserUpdate,
)
from models.config.api.workflow import (
    AnyWorkflow,
    AnyWorkflowCreate,
    FunctionDefinition,
    FunctionType,
    StreamingTable,
    StreamingWorkflow,
    StreamingWorkflowCreate,
    Table,
    TableBase,
    TableCreate,
    TableList,
    TableUpdate,
    WindowConfig,
    WindowType,
    Workflow,
    WorkflowBase,
    WorkflowCreate,
    WorkflowList,
    WorkflowType,
    WorkflowUpdate,
)

__all__ = [
    # Organization
    "Organization",
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationStatus",
    "OrganizationSettings",
    "OrganizationStats",
    "OrganizationList",
    # Bridge
    "Bridge",
    "BridgeCreate",
    "BridgeUpdate",
    "BridgeStatus",
    "BridgeType",
    "BridgeList",
    # Connector Template
    "ConnectorTemplate",
    "ConnectorTemplateCreate",
    "ConnectorTemplateUpdate",
    "TemplateVariable",
    "VariableType",
    "ConnectorTemplateList",
    "ConnectorTemplateSummary",
    # Machine
    "Machine",
    "MachineCreate",
    "MachineUpdate",
    "MachineStatus",
    "MachineProperties",
    "MachineList",
    "MachineSummary",
    # Event
    "Event",
    "EventCreate",
    "EventUpdate",
    "EventType",
    "EventList",
    "EventBulkCreate",
    # Workflow & Table
    "Workflow",
    "WorkflowCreate",
    "WorkflowUpdate",
    "WorkflowBase",
    "WorkflowList",
    "WorkflowType",
    "Table",
    "TableCreate",
    "TableUpdate",
    "TableBase",
    "TableList",
    "WindowConfig",
    "WindowType",
    "FunctionDefinition",
    "FunctionType",
    "StreamingWorkflow",
    "StreamingWorkflowCreate",
    "StreamingTable",
    "AnyWorkflowCreate",
    "AnyWorkflow",
    # User
    "User",
    "UserCreate",
    "UserUpdate",
    "UserRole",
    "UserStatus",
    "UserList",
    "OrganizationMembership",
    "LoginRequest",
    "LoginResponse",
]
